/*
 * Program calculates the cost of ordering different types of slices of pizza
 * Made by Tarkan Dahi on the 19th of Febuary, 2020
 */

/**
 *
 * @author tadah5199
 */
public class Pizzafrm extends javax.swing.JFrame {

    /**
     * Creates new form Pizzafrm
     */
    public Pizzafrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlepnl = new javax.swing.JLabel();
        promptpnl = new javax.swing.JLabel();
        Cheeselbl = new javax.swing.JLabel();
        Pepperonilbl = new javax.swing.JLabel();
        Veggielbl = new javax.swing.JLabel();
        CheeseTxt = new javax.swing.JTextField();
        PepperoniTxt = new javax.swing.JTextField();
        VeggieTxt = new javax.swing.JTextField();
        Orderbtn = new javax.swing.JButton();
        Taxeslbl = new javax.swing.JLabel();
        TaxesArealbl = new javax.swing.JLabel();
        SubtotalLbl = new javax.swing.JLabel();
        SubtotalArealbl = new javax.swing.JLabel();
        Totallbl = new javax.swing.JLabel();
        TotalArealbl = new javax.swing.JLabel();
        pizzaPicturelbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        titlepnl.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        titlepnl.setForeground(new java.awt.Color(51, 51, 255));
        titlepnl.setText("Tarkan's Pizza Store");

        promptpnl.setText("Please enter the number of pizza slices you would like to order and click Calculate.");

        Cheeselbl.setText("Cheese Pizza ($2.99):");

        Pepperonilbl.setText("Pepperoni Pizza ($3.99):");

        Veggielbl.setText("Vegetable Pizza ($3.99):");

        Orderbtn.setText("Calculate ");
        Orderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderbtnActionPerformed(evt);
            }
        });

        Taxeslbl.setText("Taxes:");

        TaxesArealbl.setText("$0.00");

        SubtotalLbl.setText("Subtotal:");

        SubtotalArealbl.setText("$0.00");

        Totallbl.setText("Total:");

        TotalArealbl.setText("$0.00");

        pizzaPicturelbl.setIcon(new javax.swing.ImageIcon("JFRCVIFS.Student.UGDSB.ED\\Home\\Students\\TaDah5199\\Documents\\20110708-new-york-pizza-dough-200x150.jpeg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Veggielbl)
                                .addGap(18, 18, 18)
                                .addComponent(VeggieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pepperonilbl)
                                    .addComponent(Cheeselbl))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheeseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PepperoniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Taxeslbl)
                                .addComponent(SubtotalLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Totallbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SubtotalArealbl, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(TaxesArealbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalArealbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pizzaPicturelbl)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(promptpnl, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(titlepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Orderbtn)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titlepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(promptpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pizzaPicturelbl))
                .addGap(18, 18, 18)
                .addComponent(Orderbtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Taxeslbl)
                    .addComponent(TaxesArealbl)
                    .addComponent(Cheeselbl)
                    .addComponent(CheeseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubtotalArealbl)
                            .addComponent(SubtotalLbl))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pepperonilbl)
                            .addComponent(PepperoniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Totallbl)
                    .addComponent(TotalArealbl)
                    .addComponent(Veggielbl)
                    .addComponent(VeggieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderbtnActionPerformed
        //Variable Declaration area
        int numCheese;
        int numPepper;
        int numVeggie;
        
        final double priceCheese = 2.99;
        final double pricePepper = 3.99;
        final double priceVeggie = 3.99;
        
        
        double tax;
        double taxRoundoff;
        double subTotal;
        double total;
        double totalRoundoff;
        
        //Area to get the number of each slice bought
        numCheese = Integer.parseInt(CheeseTxt.getText());
        numPepper = Integer.parseInt(PepperoniTxt.getText());
        numVeggie = Integer.parseInt(VeggieTxt.getText());
        
        //Calculation area for subtotal, total, and taxes. Also for the rounding of values.
        subTotal = numCheese * priceCheese + numPepper * pricePepper + numVeggie * priceVeggie;
        SubtotalArealbl.setText("$" + subTotal);
        
        tax = subTotal * 0.13;
        taxRoundoff = Math.round(tax* 100.0) / 100.0;
        TaxesArealbl.setText("$" + taxRoundoff);
        
        total = subTotal + taxRoundoff;
        TotalArealbl.setText("$" + total);
        
                
    }//GEN-LAST:event_OrderbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzafrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzafrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheeseTxt;
    private javax.swing.JLabel Cheeselbl;
    private javax.swing.JButton Orderbtn;
    private javax.swing.JTextField PepperoniTxt;
    private javax.swing.JLabel Pepperonilbl;
    private javax.swing.JLabel SubtotalArealbl;
    private javax.swing.JLabel SubtotalLbl;
    private javax.swing.JLabel TaxesArealbl;
    private javax.swing.JLabel Taxeslbl;
    private javax.swing.JLabel TotalArealbl;
    private javax.swing.JLabel Totallbl;
    private javax.swing.JTextField VeggieTxt;
    private javax.swing.JLabel Veggielbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pizzaPicturelbl;
    private javax.swing.JLabel promptpnl;
    private javax.swing.JLabel titlepnl;
    // End of variables declaration//GEN-END:variables
}
